/* =========================================================================
   MONITOR THRESHOLDS — LIMITES DE CONTROLE POR CULTURA (seed do CSV Farmbox)
   Fonte: exportacao 'estagios_ativos' (autoritativa; tem as 4 categorias +
   Inimigos Naturais + Pousio, ausentes no raw). Por (cultura, alvo, estagio):
   Controle/Dano Vegetativo + Reprodutivo + tipo de calculo + qtd max/amostra.
   Idempotente (rebuild total do seed 'farmbox'; preserva source='app').
   ATENCAO: aplicar com  sqlcmd -f 65001 -I  (le o arquivo como UTF-8 + quoted
   identifiers). Sem -f 65001 os nomes acentuados de cultura/alvo corrompem e
   nao casam por nome (perde-se ~metade das culturas + cria alvos duplicados).
   ========================================================================= */
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON; SET NOCOUNT ON; SET XACT_ABORT ON;
GO
-- categoria do alvo em FARM_PEST
IF COL_LENGTH('dbo.FARM_PEST','category') IS NULL ALTER TABLE dbo.FARM_PEST ADD category VARCHAR(20) NULL;
GO
-- niveis reprodutivos + qtd max por amostra em FARM_PEST_THRESHOLD (veg = action_level/damage_level)
IF COL_LENGTH('dbo.FARM_PEST_THRESHOLD','rep_action_level') IS NULL ALTER TABLE dbo.FARM_PEST_THRESHOLD ADD rep_action_level DECIMAL(10,3) NULL;
IF COL_LENGTH('dbo.FARM_PEST_THRESHOLD','rep_damage_level') IS NULL ALTER TABLE dbo.FARM_PEST_THRESHOLD ADD rep_damage_level DECIMAL(10,3) NULL;
IF COL_LENGTH('dbo.FARM_PEST_THRESHOLD','max_per_sample') IS NULL ALTER TABLE dbo.FARM_PEST_THRESHOLD ADD max_per_sample DECIMAL(10,3) NULL;
GO
BEGIN TRAN;
CREATE TABLE #csv (culture_name NVARCHAR(80), cat VARCHAR(20), target_name NVARCHAR(200), stage NVARCHAR(120), veg_ctrl DECIMAL(10,3), veg_dano DECIMAL(10,3), rep_ctrl DECIMAL(10,3), rep_dano DECIMAL(10,3), calc NVARCHAR(60), maxs DECIMAL(10,3));
INSERT INTO #csv (culture_name,cat,target_name,stage,veg_ctrl,veg_dano,rep_ctrl,rep_dano,calc,maxs) VALUES
(N'Pré Plantio/Pós Colheita','praga',N'Ácaro-branco',N'Presença',40.0,45.0,40.0,45.0,N'Porcentagem de Infestação',100.0),
(N'Pré Plantio/Pós Colheita','praga',N'Ácaro-rajado',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Besouro Metálico',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Caramujo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Diabrotica',N'Presença',0.1,0.3,0.2,0.5,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Grilo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Helicoverpa spp',N'Lagarta Grande maior que 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Helicoverpa spp',N'Lagarta Média 0,7 a 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Helicoverpa spp',N'Lagarta Pequena menor que 0,7 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Helicoverpa spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa Medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa Medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa Medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa Medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta Falsa medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta-da-soja',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta-da-soja',N'Lagarta Média 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta-da-soja',N'Lagarta Pequena menor que 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Lagarta-da-soja',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Larva Minadora',N'Presença',0.2,0.5,0.5,1.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Mosca-branca',N'Indice Alto',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Mosca-branca',N'Indice Baixo',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Mosca-branca',N'Índice Médio',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Mosca-branca',N'Ninfa',5.0,7.0,5.0,7.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Outras Lagartas',N'Lagarta Grande',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Outras Lagartas',N'Lagarta Pequena',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Outras Lagartas',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo Barriga Verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo Edessa',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo Formigão',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo Marrom',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo pequeno',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Percevejo-verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera  frugiperda',N'Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera  frugiperda',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera  frugiperda',N'Ovo',2.0,4.0,2.0,4.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera  frugiperda',N'Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera albula',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera albula',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera albula',N'Lagarta Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera albula',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera spp',N'menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera spp',N'Grande maior 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera spp',N'media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Spodoptera spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Tamanduá-da-soja',N'Adulto',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','praga',N'Tripes (Frankliniella spp.)',N'Adulto',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Tripes (Frankliniella spp.)',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','praga',N'Vaquinha Verde',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Algodão voluntário',N'Presença',1.0,1.2,1.0,1.2,N'Média das Quantidades',NULL),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Apaga-fogo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Buva',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Capim amargoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Capim Braquiaria',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Capim carrapicho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Capim pé-de-galinha',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Capim-colchão',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Caruru',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Erva de Santa Luzia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Erva-de-touro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Fedegoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Feijão Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Joá-de-capote',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Leiteiro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Mentrasto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Milheto voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Picão-preto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Poaia-branca',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Pré Plantio/Pós Colheita','erva_daninha',N'Trapoeraba',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mofo-branco',N'Presença',2.0,5.0,2.0,5.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-alvo',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-alvo',N'Terço Inferior',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-alvo',N'Terço Medio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-alvo',N'Terço Superior',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-de-Alternária',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-de-mirotécio',N'Presença na folha',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mancha-de-mirotécio',N'Presença na Maçã',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Mofo-branco',N'Presença',10.0,15.0,10.0,15.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Pinta Preta',N'Presença',NULL,3.0,NULL,3.0,N'Média das Quantidades',NULL),
(N'Algodão','doenca',N'Ramulária',N'Esporos',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Ramulária',N'Terço Inferior',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Ramulária',N'Terço Medio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Ramulária',N'Terço Superior',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Ramulária da mancha azul',N'mancha Azul/ esporulando',5.0,10.0,12.0,15.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','doenca',N'Virose Atípica',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Aracnídeos',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Besouro calosoma',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Crisopídeos',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Fungo Nomuraea Rileyi',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Joaninhas',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Mosca Dolichopodidae',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Mosca Tachinidae',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Percevejo Geocoris',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Percevejo Podisus',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Sirfídeos',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Tesourinhas',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa bracon',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa braconidae',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa campoletis',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa copidosoma',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa diadegma',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','inimigo_natural',N'Vespa trichogramma',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Ácaro Vermelho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Ácaro-branco',N'Presença',40.0,45.0,40.0,45.0,N'Porcentagem de Infestação',100.0),
(N'Algodão','praga',N'Ácaro-rajado',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Bicudo',N'Adulto',4.0,5.0,4.0,5.0,N'Porcentagem de Infestação',3.0),
(N'Algodão','praga',N'Bicudo',N'Botões Alim.',4.0,5.0,4.0,5.0,N'Porcentagem de Infestação',3.0),
(N'Algodão','praga',N'Bicudo',N'Botões Ovop.',NULL,NULL,4.0,5.0,N'Porcentagem de Infestação',3.0),
(N'Algodão','praga',N'Caramujo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Lagarta G (>10mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Lagarta M (3-10mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Lagarta P (até 3mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Ovo Claro',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Ovo Parasitado',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Curuquerê',N'Plantas atacadas',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Grilo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Lagarta G (>10mm)',5.0,6.0,5.0,6.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Lagarta M (3-10mm)',5.0,6.0,5.0,6.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Lagarta P (até 3mm)',5.0,6.0,5.0,6.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Ovo Claro',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Ovo Parasitado',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Helicoverpa spp',N'Plantas atacadas',5.0,6.0,5.0,6.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Lagarta G (>10mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Lagarta M (3-10mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Lagarta P (até 3mm)',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Ovo Claro',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Ovo Parasitado',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Lagarta Falsa Medideira',N'Plantas atacadas',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Larva Minadora',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Mosca-branca',N'Adulto',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Mosca-branca',N'Ninfa',7.0,10.0,7.0,10.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Percevejo spp.',N'Caminhamento',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Percevejo spp.',N'Ponto',10.0,11.0,10.0,11.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Pulgão do Algodoeiro',N'Alado',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Pulgão do Algodoeiro',N'Colônia G',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Pulgão do Algodoeiro',N'Colônia Pq (até 10)',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Lagarta G (>10mm)',6.0,6.5,6.0,6.5,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Lagarta M (3-10mm)',6.0,6.5,6.0,6.5,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Lagarta P (até 3mm)',6.0,6.5,6.0,6.5,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Ovo Claro',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Ovo Parasitado',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Spodoptera spp',N'Plantas atacadas',6.0,6.5,6.0,6.5,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Tripes (Frankliniella spp.)',N'Adulto',20.0,22.0,40.0,45.0,N'Porcentagem de Infestação',1.0),
(N'Algodão','praga',N'Tripes (Frankliniella spp.)',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Algodão voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Apaga-fogo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Buva',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Capim amargoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Capim Braquiaria',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Capim carrapicho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Capim pé-de-galinha',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Capim-colchão',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Caruru',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Erva de Santa Luzia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Erva-de-touro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Fedegoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Feijão Tiguera',N'Danos por Tripes',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Feijão Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Algodão','erva_daninha',N'Joá-de-capote',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Leiteiro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Mentrasto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Milheto voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Picão-preto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Poaia-branca',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Algodão','erva_daninha',N'Trapoeraba',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Ácaro-branco',N'Presença',40.0,45.0,40.0,45.0,N'Porcentagem de Infestação',100.0),
(N'Braquiária','praga',N'Ácaro-rajado',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Besouro Metálico',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Diabrotica',N'Presença',0.1,0.3,0.2,0.5,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Helicoverpa spp',N'Lagarta Grande maior que 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Helicoverpa spp',N'Lagarta Média 0,7 a 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Helicoverpa spp',N'Lagarta Pequena menor que 0,7 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Helicoverpa spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Lagarta Falsa Medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta Falsa Medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta Falsa Medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta Falsa Medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Lagarta-da-soja',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta-da-soja',N'Lagarta Média 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta-da-soja',N'Lagarta Pequena menor que 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Lagarta-da-soja',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Larva Minadora',N'Presença',0.2,0.5,0.5,1.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Mosca-branca',N'Indice Alto',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Mosca-branca',N'Indice Baixo',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Mosca-branca',N'Índice Médio',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Mosca-branca',N'Ninfa',5.0,7.0,5.0,7.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Outras Lagartas',N'Lagarta Grande',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Outras Lagartas',N'Lagarta Pequena',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Outras Lagartas',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Percevejo Barriga Verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Percevejo Edessa',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Percevejo Formigão',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Percevejo Marrom',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Percevejo pequeno',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Percevejo-verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera  frugiperda',N'Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera  frugiperda',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera  frugiperda',N'Ovo',2.0,4.0,2.0,4.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Spodoptera  frugiperda',N'Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera albula',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera albula',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera albula',N'Lagarta Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera albula',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Spodoptera spp',N'menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera spp',N'Grande maior 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera spp',N'media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Spodoptera spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Tamanduá-da-soja',N'Adulto',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Braquiária','praga',N'Tripes (Frankliniella spp.)',N'Adulto',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Tripes (Frankliniella spp.)',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Braquiária','praga',N'Vaquinha Verde',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Café','doenca',N'Cercospora',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Cercosporiose',N'Frutos com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Boro',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de cálcio',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de cobre',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Enxofre',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Ferro',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Fosforo',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Magnésio',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Manganês',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Nitrogênio',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Potássio',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Deficiência de Zinco',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Ferrugem do cafeeiro',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Mancha Aureolada',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Nematóide de galhas',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Nematóide Pratylenchus',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','doenca',N'Phoma',N'Folhas com sintoma',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Ácaro da leprose',N'Folhas com o alvo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Ácaro Vermelho do Café',N'Folhas com o alvo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Ácaro-branco',N'Folhas com o alvo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Bicho Mineiro',N'Adulto - Alta Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Bicho Mineiro',N'Adulto - Baixa Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Bicho Mineiro',N'Adulto - Média Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Bicho Mineiro',N'Folhas com larva',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Bicho Mineiro',N'Folhas com ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Bicho Mineiro',N'Folhas com pulpa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',60.0),
(N'Café','praga',N'Broca do Café',N'Adulta Viva - Alta Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Broca do Café',N'Adulta Viva - Baixa Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Broca do Café',N'Adulta Viva - Média Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Broca do Café',N'grãos brocados',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',10.0),
(N'Café','praga',N'Cochonilha das rosetas',N'Presença - Alta pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Cochonilha das rosetas',N'Presença - Baixa Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Cochonilha das rosetas',N'Presença - Média Pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lagarta Falsa medideira',N'Alta pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lagarta Falsa medideira',N'Baixa pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lagarta Falsa medideira',N'Média pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lesma',N'Alta pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lesma',N'Baixa pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Lesma',N'Média pressão',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','praga',N'Mosca-branca',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','erva_daninha',N'Capim amargoso',N'Grande',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','erva_daninha',N'Capim amargoso',N'Média',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Café','erva_daninha',N'Capim amargoso',N'Pequena',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Mofo-branco',N'Presença',0.5,1.0,0.5,1.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Antracnose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Cercosporiose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',25.0),
(N'Feijão','doenca',N'Crestamento Bacteriano',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Ferrugem da Soja',N'Presença',5.0,6.0,5.0,6.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Fusarium',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Mancha-alvo',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Mancha-parda / Septoriose',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Mela',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Míldio',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Mofo-branco',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','doenca',N'Nematóide de galhas',N'Reboleira',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Oídio',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','doenca',N'Sarna-do-feijoeiro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Aracnídeos',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Besouro calosoma',N'Adulto',1.0,NULL,1.0,NULL,N'Média das Quantidades',NULL),
(N'Feijão','inimigo_natural',N'Crisopídeos',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Insetos Benéficos',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','inimigo_natural',N'Joaninhas',N'Adulto, ninfas e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Mosca Dolichopodidae',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Mosca Sirfídeos',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Mosca Tachinidae',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Percevejo Podisus',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Tesourinhas',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Vespa braconidae',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Vespa campoletis',N'Adulto e pupas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Vespa copidosoma',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','inimigo_natural',N'Vespa diadegma',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Ácaro-branco',N'Presença',40.0,45.0,40.0,45.0,N'Porcentagem de Infestação',100.0),
(N'Feijão','praga',N'Ácaro-rajado',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Besouro Metálico',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Cigarrinha',N'Adulto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Feijão','praga',N'Cigarrinha',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Feijão','praga',N'Cigarrinha',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Diabrotica',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Helicoverpa spp',N'Grande maior que 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Helicoverpa spp',N'Lagarta Média 0,7 a 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Helicoverpa spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Helicoverpa spp',N'Pequena menor que 0,7 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Lagarta Falsa Medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Porcentagem de Infestação',15.0),
(N'Feijão','praga',N'Lagarta Falsa Medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Porcentagem de Infestação',15.0),
(N'Feijão','praga',N'Lagarta Falsa Medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',15.0),
(N'Feijão','praga',N'Lagarta Falsa Medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Porcentagem de Infestação',15.0),
(N'Feijão','praga',N'Lagarta-da-soja',N'Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Lagarta-da-soja',N'Lagarta Média 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Lagarta-da-soja',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Lagarta-da-soja',N'Pequena menor que 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Larva Minadora',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Mosca-branca',N'Indice Alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Mosca-branca',N'Indice Baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Mosca-branca',N'Índice Médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Mosca-branca',N'Ninfa',7.0,10.0,7.0,10.0,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Outras Lagartas',N'Lagarta Grande',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Outras Lagartas',N'Lagarta Pequena',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Outras Lagartas',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Percevejo Barriga Verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Percevejo Edessa',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Percevejo Marrom',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Percevejo pequeno',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Percevejo-verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera  frugiperda',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera  frugiperda',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera  frugiperda',N'Lagarta Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera  frugiperda',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Spodoptera albula',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera albula',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera albula',N'Lagarta Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Spodoptera albula',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Tamanduá-da-soja',N'Adulto',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Feijão','praga',N'Tripes (Frankliniella spp.)',N'Adulto',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Tripes (Frankliniella spp.)',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','praga',N'Vaquinha Verde',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Feijão','erva_daninha',N'Algodão voluntário',N'Presença',1.0,1.2,1.0,1.2,N'Média das Quantidades',NULL),
(N'Feijão','erva_daninha',N'Apaga-fogo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Buva',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Capim amargoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Capim carrapicho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Capim pé-de-galinha',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Capim-colchão',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Caruru',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Erva de Santa Luzia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Erva-de-touro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Fedegoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Joá-de-capote',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Leiteiro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Mentrasto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Milheto voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Milho Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Picão-preto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Poaia-branca',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Feijão','erva_daninha',N'Trapoeraba',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Diplodia',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Enfezamento-vermelho',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Erwinia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Ferrugem polissora',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Helmintosporiose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milheto','doenca',N'Mancha Branca',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Ácaro-rajado',N'Colônia',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Ácaro-rajado',N'Colônia+',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Ácaro-rajado',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Broca do Colmo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Cigarrinha das Pastagens',N'Adulto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Cigarrinha das Pastagens',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Cigarrinha das Pastagens',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Cigarrinha do Milho',N'Adulto',1.0,1.5,5.0,7.0,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Cigarrinha do Milho',N'Ninfa',0.5,2.0,5.0,10.0,N'Porcentagem de Infestação',10.0),
(N'Milheto','praga',N'Cigarrinha do Milho',N'Presença',2.0,5.0,2.0,5.0,N'Porcentagem de Infestação',10.0),
(N'Milheto','praga',N'Helicoverpa zea',N'Grande >8 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Helicoverpa zea',N'Mariposa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Helicoverpa zea',N'Média 4-7 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Helicoverpa zea',N'Ovos',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Helicoverpa zea',N'Pequena 1-3 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Mosca da Espiga Euxesta',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','praga',N'Mosca-branca',N'Índice Alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Mosca-branca',N'Índice Baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Mosca-branca',N'Índice Médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Mosca-branca',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Percevejo Escuro',N'Adulto',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','praga',N'Percevejo spp.',N'Adulto',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','praga',N'Percevejo spp.',N'Ninfa',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','praga',N'Percevejo spp.',N'Postura de ovos',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','praga',N'Pulgão-do-milho',N'C',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Pulgão-do-milho',N'C+',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Pulgão-do-milho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Spodoptera  frugiperda',N'Grande >8 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Spodoptera  frugiperda',N'Mariposa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','praga',N'Spodoptera  frugiperda',N'Média 4-7 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Spodoptera  frugiperda',N'Ovos',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Spodoptera  frugiperda',N'Pequena 1-3 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Tripes (Frankliniella spp.)',N'Adulto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Tripes (Frankliniella spp.)',N'Ninfas',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milheto','praga',N'Vaquinha/ Patriota',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milheto','erva_daninha',N'Algodão voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Apaga-fogo',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Apaga-fogo',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Apaga-fogo',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Beldroega',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Beldroega',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Beldroega',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Braquiária',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Braquiária',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Braquiária',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Buva',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Buva',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Buva',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim amargoso',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim amargoso',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim amargoso',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim carrapicho',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim carrapicho',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim carrapicho',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Colonião',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Colonião',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Colonião',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Mombaça',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Mombaça',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Mombaça',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim pé-de-galinha',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim pé-de-galinha',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim pé-de-galinha',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Rabo-de-raposa',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Rabo-de-raposa',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim Rabo-de-raposa',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim-colchão',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim-colchão',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Capim-colchão',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Caruru',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Caruru',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Caruru',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Corda de Viola',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Corda de Viola',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Corda de Viola',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva de Santa Luzia',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva de Santa Luzia',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva de Santa Luzia',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-de-touro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-de-touro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-de-touro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-quente',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-quente',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-quente',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Fedegoso',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Fedegoso',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Fedegoso',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Guanxuma',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Guanxuma',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Guanxuma',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Joá-de-capote',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Joá-de-capote',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Joá-de-capote',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Leiteiro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Leiteiro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Leiteiro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Malícia',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Malícia',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Malícia',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Mentrasto',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Mentrasto',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Mentrasto',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão-preto',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão-preto',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Picão-preto',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Tiririca',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Tiririca',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Tiririca',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Trapoeraba',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Trapoeraba',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milheto','erva_daninha',N'Trapoeraba',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Antracnose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Bipolaris maydis',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Cercospora',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Diplodia',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Enfezamento-pálido',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Enfezamento-vermelho',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Erwinia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Ferrugem polissora',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Ferrugem-branca',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Helmintosporiose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','doenca',N'Mancha Branca',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Ácaro-rajado',N'Colônia',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Ácaro-rajado',N'Colônia+',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Ácaro-rajado',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Broca do Colmo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0);
INSERT INTO #csv (culture_name,cat,target_name,stage,veg_ctrl,veg_dano,rep_ctrl,rep_dano,calc,maxs) VALUES
(N'Milho','praga',N'Cigarrinha das Pastagens',N'Adulto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Cigarrinha das Pastagens',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Cigarrinha das Pastagens',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Cigarrinha do Milho',N'Adulto',1.0,1.5,5.0,7.0,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Cigarrinha do Milho',N'Ninfa',0.5,2.0,5.0,10.0,N'Porcentagem de Infestação',10.0),
(N'Milho','praga',N'Cigarrinha do Milho',N'Presença',2.0,5.0,2.0,5.0,N'Porcentagem de Infestação',10.0),
(N'Milho','praga',N'Helicoverpa zea',N'Grande >8 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Helicoverpa zea',N'Mariposa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Helicoverpa zea',N'Média 4-7 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Helicoverpa zea',N'Ovos',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Helicoverpa zea',N'Pequena 1-3 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Mosca da Espiga Euxesta',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','praga',N'Mosca-branca',N'Índice Alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Mosca-branca',N'Índice Baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Mosca-branca',N'Índice Médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Mosca-branca',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Percevejo Escuro',N'Adulto',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','praga',N'Percevejo spp.',N'Adulto',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','praga',N'Percevejo spp.',N'Ninfa',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','praga',N'Percevejo spp.',N'Postura de ovos',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','praga',N'Pulgão-do-milho',N'C',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Pulgão-do-milho',N'C+',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Pulgão-do-milho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Spodoptera  frugiperda',N'Grande >8 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Spodoptera  frugiperda',N'Mariposa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','praga',N'Spodoptera  frugiperda',N'Média 4-7 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Spodoptera  frugiperda',N'Ovos',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Spodoptera  frugiperda',N'Pequena 1-3 mm',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Tripes (Frankliniella spp.)',N'Adulto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Tripes (Frankliniella spp.)',N'Ninfas',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',5.0),
(N'Milho','praga',N'Vaquinha/ Patriota',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','erva_daninha',N'Capim marmelada',N'Nível alto',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Milho','erva_daninha',N'Capim marmelada',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim marmelada',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Algodão voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Apaga-fogo',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Apaga-fogo',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Apaga-fogo',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Beldroega',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Beldroega',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Beldroega',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Braquiária',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Braquiária',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Braquiária',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Buva',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Buva',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Buva',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim amargoso',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim amargoso',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim amargoso',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim carrapicho',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim carrapicho',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim carrapicho',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Colonião',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Colonião',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Colonião',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Mombaça',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Mombaça',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Mombaça',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim pé-de-galinha',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim pé-de-galinha',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim pé-de-galinha',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Rabo-de-raposa',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Rabo-de-raposa',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim Rabo-de-raposa',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim-colchão',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim-colchão',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Capim-colchão',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Caruru',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Caruru',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Caruru',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Corda de Viola',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Corda de Viola',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Corda de Viola',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva de Santa Luzia',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva de Santa Luzia',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva de Santa Luzia',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-de-touro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-de-touro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-de-touro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-quente',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-quente',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-quente',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Fedegoso',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Fedegoso',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Fedegoso',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Guanxuma',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Guanxuma',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Guanxuma',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Joá-de-capote',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Joá-de-capote',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Joá-de-capote',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Leiteiro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Leiteiro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Leiteiro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Malícia',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Malícia',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Malícia',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Mentrasto',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Mentrasto',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Mentrasto',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Milho voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão Branco/Fazendeiro',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão-preto',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão-preto',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Picão-preto',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Tiririca',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Tiririca',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Tiririca',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Trapoeraba',N'Nível alto',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Trapoeraba',N'Nível baixo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Milho','erva_daninha',N'Trapoeraba',N'Nível médio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Mofo-branco',N'Apotecio',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Mofo-branco',N'Presença',0.5,1.0,0.5,1.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Antracnose',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Cercosporiose',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Crestamento Bacteriano',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Ferrugem da Soja',N'Presença',5.0,6.0,5.0,6.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Fusarium',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Mancha-alvo',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Mancha-parda / Septoriose',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Mela',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Míldio',N'Presença',20.0,25.0,20.0,25.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Mofo-branco',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','doenca',N'Nematóide de galhas',N'Reboleira',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','doenca',N'Oídio',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Aracnídeos',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Besouro calosoma',N'Adulto',1.0,NULL,1.0,NULL,N'Média das Quantidades',NULL),
(N'Soja','inimigo_natural',N'Crisopídeos',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Insetos Benéficos',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','inimigo_natural',N'Joaninhas',N'Adulto, ninfas e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Lysiphlebus',N'Adultos e múmias de pulgão',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Mosca Sirfídeos',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Mosca Tachinidae',N'Adulto e larvas',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','inimigo_natural',N'Percevejo Podisus',N'Adulto',1.0,NULL,1.0,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Ácaro-branco',N'Presença',40.0,45.0,40.0,45.0,N'Porcentagem de Infestação',100.0),
(N'Soja','praga',N'Ácaro-rajado',N'Presença',20.0,25.0,20.0,25.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Besouro Metálico',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Caramujo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Diabrotica',N'Presença',0.1,0.3,0.2,0.5,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Grilo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Helicoverpa spp',N'Lagarta Grande maior que 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Helicoverpa spp',N'Lagarta Média 0,7 a 1,5 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Helicoverpa spp',N'Lagarta Pequena menor que 0,7 cm',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Helicoverpa spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Helicoverpa spp',N'Somatório',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa Medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa Medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa medideira',N'Grande maior que 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa Medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa medideira',N'Lagarta Média 0,7 a 1,5 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa Medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Lagarta Falsa medideira',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Lagarta Falsa medideira',N'Pequena menor que 0,7 cm',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa Medideira',N'Somatório',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta Falsa medideira',N'Somatório',10.0,15.0,10.0,15.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-da-soja',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-da-soja',N'Lagarta Média 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-da-soja',N'Lagarta Pequena menor que 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-da-soja',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Lagarta-da-soja',N'Somatório',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-rosca',N'Lagarta Grande',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-rosca',N'Lagarta Média',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-rosca',N'Lagarta Pequena',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Lagarta-rosca',N'Ovos',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Larva Minadora',N'Presença',0.2,0.5,0.5,1.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Mosca-branca',N'Indice Alto',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Mosca-branca',N'Indice Baixo',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Mosca-branca',N'Índice Médio',30.0,50.0,30.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Mosca-branca',N'Ninfa',5.0,7.0,5.0,7.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Outras Lagartas',N'Lagarta Grande',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Outras Lagartas',N'Lagarta Pequena',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Outras Lagartas',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Percevejo Barriga Verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Percevejo Edessa',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Percevejo Formigão',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Percevejo Marrom',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Percevejo pequeno',N'Presença',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Percevejo-verde',N'Percevejo',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera  frugiperda',N'Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera  frugiperda',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera  frugiperda',N'Ovo',2.0,4.0,2.0,4.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Spodoptera  frugiperda',N'Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera  frugiperda',N'Somatório',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera albula',N'Lagarta Grande maior que 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera albula',N'Lagarta media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera albula',N'Lagarta Pequena menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera albula',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Spodoptera albula',N'Somatório',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera spp',N'menor 0,7 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera spp',N'Grande maior 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera spp',N'media 0,7 a 1,5 cm',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Spodoptera spp',N'Ovo',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Spodoptera spp',N'Somatório',2.0,3.0,2.0,3.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Tamanduá-da-soja',N'Adulto',1.0,2.0,1.0,2.0,N'Média das Quantidades',NULL),
(N'Soja','praga',N'Tripes (Frankliniella spp.)',N'Adulto',40.0,50.0,40.0,50.0,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Tripes (Frankliniella spp.)',N'Ninfa',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','praga',N'Vaquinha Verde',N'Presença',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Soja','erva_daninha',N'Algodão voluntário',N'Presença',1.0,1.2,1.0,1.2,N'Média das Quantidades',NULL),
(N'Soja','erva_daninha',N'Apaga-fogo',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Beldroega',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Buva',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Capim amargoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Capim Braquiaria',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Capim carrapicho',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Capim pé-de-galinha',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Capim-colchão',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Caruru',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Corda de Viola',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Erva de Santa Luzia',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Erva-de-touro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Erva-quente',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Fedegoso',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Feijão Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Joá-de-capote',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Leiteiro',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Mentrasto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Milheto voluntário',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Picão-preto',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Poaia-branca',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Soja Tiguera',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Soja','erva_daninha',N'Trapoeraba',N'Presença',NULL,NULL,NULL,NULL,N'Porcentagem de Infestação',1.0),
(N'Sorgo','doenca',N'Antracnose',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','doenca',N'Ferrugem comum',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','doenca',N'Helmintosporiose',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','doenca',N'Míldio do sorgo',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Ácaro-rajado',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Broca do Colmo',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Helicoverpa zea',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Lagarta Elasmo',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Lagarta-do-cartucho do milho',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Lagarta-militar',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Percevejo do milho',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Percevejo-verde',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Pulgão',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Pulgão-do-milho',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','praga',N'Pulgão-verde',N'OVOS OU PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Algodão Tiguera',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Beldroega',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Capim amargoso',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Capim pé-de-galinha',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Caruru',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Erva de Santa Luzia',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Erva-de-touro',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Picao preto',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL),
(N'Sorgo','erva_daninha',N'Soja Tiguera',N'PRESENÇA',NULL,NULL,NULL,NULL,N'Média das Quantidades',NULL);
-- 'Pre Plantio/Pos Colheita' = Pousio
UPDATE #csv SET culture_name = 'Pousio' WHERE culture_name = N'Pré Plantio/Pós Colheita';
-- cria alvos faltantes (por nome normalizado) com categoria
INSERT INTO dbo.FARM_PEST (name, category)
SELECT MIN(c.target_name), MIN(c.cat) FROM #csv c
WHERE NOT EXISTS (SELECT 1 FROM dbo.FARM_PEST pe WHERE LOWER(LTRIM(RTRIM(pe.name))) = LOWER(LTRIM(RTRIM(c.target_name))) COLLATE Latin1_General_CI_AI AND pe.deleted_at IS NULL)
GROUP BY LOWER(LTRIM(RTRIM(c.target_name)));
-- categoria nos alvos existentes
UPDATE pe SET pe.category = x.cat
FROM dbo.FARM_PEST pe
JOIN (SELECT LOWER(LTRIM(RTRIM(target_name))) nm, MIN(cat) cat FROM #csv GROUP BY LOWER(LTRIM(RTRIM(target_name)))) x
  ON LOWER(LTRIM(RTRIM(pe.name))) = x.nm COLLATE Latin1_General_CI_AI
WHERE pe.deleted_at IS NULL AND (pe.category IS NULL OR pe.category <> x.cat);
-- calc -> value_type
-- rebuild do seed: remove tudo que NAO foi editado pelo agronomo (source<>'app')
DELETE FROM dbo.FARM_PEST_THRESHOLD WHERE source <> 'app';
INSERT INTO dbo.FARM_PEST_THRESHOLD (pest_id, culture_id, param_name, phase, action_level, damage_level, rep_action_level, rep_damage_level, value_type, max_per_sample, source)
SELECT j.pest_id, j.culture_id, j.stage, 'all', MAX(j.veg_ctrl), MAX(j.veg_dano), MAX(j.rep_ctrl), MAX(j.rep_dano), MAX(j.vt), MAX(j.maxs), 'farmbox'
FROM (
  SELECT pe.id AS pest_id, cu.id AS culture_id, s.stage, s.veg_ctrl, s.veg_dano, s.rep_ctrl, s.rep_dano,
         CASE s.calc WHEN N'Média das Quantidades' THEN 'average_type' WHEN N'Porcentagem de Infestação' THEN 'percentage_type' WHEN N'Presença ou Ausência' THEN 'presence_type' ELSE NULL END AS vt,
         s.maxs
  FROM (
    SELECT c.culture_name, c.target_name, c.stage, MAX(c.veg_ctrl) veg_ctrl, MAX(c.veg_dano) veg_dano,
           MAX(c.rep_ctrl) rep_ctrl, MAX(c.rep_dano) rep_dano, MAX(c.calc) calc, MAX(c.maxs) maxs
    FROM #csv c GROUP BY c.culture_name, c.target_name, c.stage
  ) s
  JOIN dbo.FARM_CULTURE cu ON cu.name = s.culture_name COLLATE Latin1_General_CI_AI AND cu.deleted_at IS NULL
  JOIN dbo.FARM_PEST pe ON LOWER(LTRIM(RTRIM(pe.name))) = LOWER(LTRIM(RTRIM(s.target_name))) COLLATE Latin1_General_CI_AI AND pe.deleted_at IS NULL
) j
-- nao sobrescreve chave (pest,param,phase,culture) editada pelo agronomo; ignora deleted_at DE
-- PROPOSITO: um limite que o agronomo APAGOU (tombstone source='app') NAO deve ser ressuscitado.
WHERE NOT EXISTS (SELECT 1 FROM dbo.FARM_PEST_THRESHOLD t WHERE t.pest_id=j.pest_id AND t.culture_id=j.culture_id AND t.param_name=j.stage AND t.phase='all')
GROUP BY j.pest_id, j.culture_id, j.stage;
COMMIT;
GO
SELECT 'FARM_PEST c/ categoria' t, COUNT(*) n FROM dbo.FARM_PEST WHERE category IS NOT NULL AND deleted_at IS NULL
UNION ALL SELECT 'FARM_PEST_THRESHOLD total', COUNT(*) FROM dbo.FARM_PEST_THRESHOLD WHERE deleted_at IS NULL
UNION ALL SELECT 'THRESHOLD c/ culture', COUNT(*) FROM dbo.FARM_PEST_THRESHOLD WHERE culture_id IS NOT NULL AND deleted_at IS NULL
UNION ALL SELECT 'culturas distintas', COUNT(DISTINCT culture_id) FROM dbo.FARM_PEST_THRESHOLD WHERE deleted_at IS NULL;
GO